apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
  labels:
    type: db
spec:
  replicas: 3
  selector:
    matchLabels:
      type: db
  template:
    metadata:
      name: postgrs-pod
      labels:
         type: db
    spec:
       containers:
          - name: mypostgres
            image: postgres
            env:
             - name: POSTGRES_PASSWORD
               valueFrom:
                  secretKeyRef:
                       name: secret2
                       key: password
             - name: POSTGRES_USER
               valueFrom:
                  secretKeyRef:
                       name: secret2
                       key: username
             - name: POSTGRES_DB
               valueFrom:
                  secretKeyRef:
                       name: secret2
                       key: mydb     

