apiVersion: v1
kind: Pod
metadata:
  name: postgress-pd
  labels:
    type: db
    author: vivek
spec:
  containers:
    - image: postgres
      name: mydb
      env:
        - name: POSTGRES_PASSWORD
          value: vivek12
        - name: POSTGRES_USER
          value: vivek
        - name: POSTGRES_DB
          value: mydb
