---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deplyment
  labels:
    type: proxy
spec:
  replicas: 3
  selector:
    matchLabels:
      type: proxy
  template:
    metadata:
      name: nginx-dp
      labels:
        type: proxy
    spec:
      containers:
        - name: mynginx
          image: nginx
          ports:
            - containerPort: 80
              hostPort: 8080
