---
apiVersion: v1
kind: Pod
metadata:
  name: httpd-pd
  labels:
    type: webserver
    author: vivek
spec:
  containers:
      - name: myhttpd
        image: httpd
        ports:
          - containerPort: 80
            hostPort: 9090
