---
apiVersion: v1
kind: Pod
metadata:
  name: cicd
  labels:
    type: jenkisci-cd
    author: vivek
spec:
  containers:
    - name: myjenkins
      image: jenkins/jenkins
      ports:
        - containerPort: 8080
          hostPort: 7070
