---
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  labels:
    type: postgres
    author: vivek
spec:
  ports:
    - targetPort: 5432
      port: 5432
  selector:
    type: postgres
...
