---
apiVersion: v1
kind: Service
metadata:
  name: voting-app-service
  labels:
    type: votingappservice
    author: vivek
spec:
  type: LoadBalancer
  ports:
    - targetPort: 80
      port: 80
      nodePort: 30008
  selector:
    type: voting-app
...
